[project]
name = "EMT_data_analysis"
version = "0.0.0"
description = "EMT data analysis scripts"
authors = [
    {email = "cells@alleninstitute.org"},
]
dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.2.2",
    "scipy>=1.13.1",
    "aicsimageio>=4.14.0",
    "tqdm>=4.66.4",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "AISL"}

[project.optional-dependencies]
internal = [
    "aicsfiles>=4.1.1",
]
